### ISSUE TITLE
Which metric setting did you report in your paper?

### ISSUE THREAD

**Issue by yaoxingcheng** [uclanlp/ParaBART#1]
Would you mind elaborating on the detailed evaluation setting in SentEval to produce the numbers in your paper. Specifically, for STS12-16 tasks, did you report `wmean` or `mean` of Pearman's correlation?

**Comment by jyhuang36** [comment]
Hi, we report `mean` of Pearson's correlation for STS12-16 tasks.

**Comment by yaoxingcheng** [comment]
Thanks!
