### ISSUE TITLE
Hows this data file (data.h5) is created?

### ISSUE THREAD

**Issue by sabirdvd** [uclanlp/ParaBART#2]
Thank you for sharing this interesting work. Hows this data file (data.h5) is created?  I'm trying to train QQP task (Table 3) which is csv files. Thanks.

**Comment by jyhuang36** [comment]
The training data is created using the `h5py` package. However, our model is evaluated on QQP datasets without training on any QQP data. You can follow the instructions on how to evaluate our model on QQP datasets.

**Comment by jyhuang36** [comment]
Hi, the training data is created using the `h5py` package. However, our model is evaluated on QQP datasets without training on any QQP data. You can follow the instructions on how to evaluate our model on QQP datasets.
